# CONFIG FILE TO CALIBRATE PREFERENCE PARAMETERS FOR SOCIAL CARE ANALYSIS
# MODEL INCLUDES RATIONAL RESPONSES WITHOUT CARE AND POPULATION ALIGNMENT
countryString: "United Kingdom"
maxNumberOfRuns: 1
executeWithGui: false
randomSeed: 606
startYear: 2019
endYear: 2020
popSize: 170000

# Arguments passed to the SimPathsModel
model_args:
    maxAge: 130
    fixTimeTrend: true
    timeTrendStopsIn: 2021
    timeTrendStopsInMonetaryProcesses: 2021
    fixRandomSeed: true
    savingRate: 0.056
    initialisePotentialEarningsFromDatabase: true
    useWeights: false
    ignoreTargetsAtPopulationLoad: false
    projectMortality: true
    alignPopulation: true
    alignFertility: false
    alignEducation: false
    alignInSchool: false
    alignCohabitation: false
    alignEmployment: false
    addRegressionStochasticComponent: true
    fixRegressionStochasticComponent: false
    labourMarketCovid19On: false
    projectFormalChildcare: true
    donorPoolAveraging: true
    projectSocialCare: false
    flagSuppressChildcareCosts: false
    flagSuppressSocialCareCosts: false
    enableIntertemporalOptimisations: true
    saveBehaviour: false
    useSavedBehaviour: false
    readGrid: "temp"
    flagDefaultToTimeSeriesAverages: true
    saveImperfectTaxDBMatches: false
    employmentOptionsOfPrincipalWorker: 3
    employmentOptionsOfSecondaryWorker: 3
    responsesToEducation: true
    responsesToPension: false
    responsesToLowWageOffer: true
    responsesToRetirement: false
    responsesToHealth: true
    responsesToDisability: false
    minAgeForPoorHealth: 45
    responsesToRegion: false

# Arguments that alter processing of the SimPathsMultiRun object
innovation_args:
    randomSeedInnov: false
    flagDatabaseSetup: false
    intertemporalElasticityInnov: false
    labourSupplyElasticityInnov: false

collector_args:
#    calculateGiniCoefficients: false
#    exportToDatabase: false
#    exportToCSV: true
#    persistStatistics: true
#    persistStatistics2: true
#    persistPersons: false
#    persistBenefitUnits: false
#    persistHouseholds: false
#    dataDumpStartTime: 0L
#    dataDumpTimePeriod: 1.0